# Generated by Django 5.0.7 on 2024-07-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='Description not provided.', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Title not provided.', max_length=64),
        ),
    ]
