# Generated by Django 5.0.7 on 2024-07-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_description_alter_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='updated_at',
            new_name='last_updated',
        ),
    ]
