# Generated by Django 5.0.7 on 2024-08-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_comment_options_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpvoteTracker',
            new_name='Upvote',
        ),
    ]
